import streamlit as st
from ultralytics import YOLO
from PIL import Image
import os

# --- PAGE CONFIGURATION ---
st.set_page_config(page_title="StationGuardian AI", page_icon="🚀", layout="wide")

# --- LOAD MODEL ---
@st.cache_resource
def load_model():
    model_path = os.path.join("models", "best.pt")
    try:
        return YOLO(model_path)
    except Exception as e:
        st.error(f"Error loading model: {e}. Please ensure 'models/best.pt' exists.")
        return None

model = load_model()

# --- SIDEBAR: MISSION CONTROL ---
st.sidebar.title("🛰️ Mission Control")
st.sidebar.info("System Status: Online")
app_mode = st.sidebar.selectbox("Select Module", ["Object Detection", "Falcon Update (Admin)"])

# --- MAIN APP: DETECTION ---
if app_mode == "Object Detection":
    st.title("👨‍🚀 StationGuardian: Safety Object Detection")
    st.markdown("""
    **Operational Context:** This system assists astronauts in locating vital safety equipment 
    (Oxygen Tanks, Fire Extinguishers) during emergencies on the ISS.
    """)

    uploaded_file = st.file_uploader("Upload Station Feed (Image)", type=["jpg", "png", "jpeg"])

    if uploaded_file is not None:
        col1, col2 = st.columns(2)
        
        with col1:
            st.subheader("Raw Feed")
            image = Image.open(uploaded_file)
            st.image(image, use_column_width=True)

        with col2:
            st.subheader("AI Analysis")
            if st.button("Analyze Safety Objects", type="primary"):
                if model:
                    with st.spinner('Scanning neural network...'):
                        results = model.predict(image, conf=0.5)
                        res_plotted = results[0].plot()
                        st.image(res_plotted, caption='Detected Safety Equipment', use_column_width=True)
                        
                        # Metrics Display
                        boxes = results[0].boxes
                        if boxes:
                            st.success(f"Confirmed: {len(boxes)} Safety Objects Found")
                            for box in boxes:
                                name = model.names[int(box.cls[0])]
                                conf = float(box.conf[0])
                                st.write(f"✅ **{name}** - Confidence: {conf:.2%}")
                        else:
                            st.warning("No known safety objects detected in this sector.")

# --- BONUS: FALCON UPDATE PIPELINE (Page 11 Requirement) ---
elif app_mode == "Falcon Update (Admin)":
    st.title("🔄 Falcon Model Maintenance Pipeline")
    st.markdown("### Continuous Integration with Digital Twins")
    
    st.write("""
    This module demonstrates how **Duality Falcon** keeps the AI model up-to-date when new 
    equipment is installed on the station.
    """)
    
    st.info("ℹ️ **Scenario:** A new 'Radiation Shield' has been installed on the ISS. The current model cannot detect it.")
    
    with st.expander("Step 1: Ingest Synthetic Data"):
        st.write("Importing 5,000 synthetic images of 'Radiation Shield' generated by Falcon...")
        st.progress(100)
        st.caption("Data Ingestion Complete.")
        
    with st.expander("Step 2: Trigger Retraining"):
        if st.button("Start Remote Training"):
            st.write("🚀 Training Job #4092 initiated on GPU Cluster.")
            st.write("⏳ Estimated time: 45 minutes.")
            st.success("Pipeline Active. Model version v2.0 will be deployed automatically upon completion.")